### ISSUE TITLE
/dev/fb0 vertical refresh is running at 120Hz

### ISSUE THREAD

**Issue by jwinarske** [TechNexion/meta-edm-bsp-release#4]
Rocko / PICO-PI-IMX7

root@pico-imx7:~# cat /sys/class/graphics/fb0/modes
U:480x272p-120
U:480x272i-120

Should be no more than 60Hz, or it's burning power for no good reason...

**Comment by richard-hu** [comment]
@jwinarske 

For PICO-IMX7,  the default panel is 5-inch 800x480 parallel LCD in Yocto 2.4 release image: 

ftp://ftp.technexion.net/demo_software/pico-imx7-sd/pico-imx7_pico-pi_yocto-2.4-qt5_sdcard-preview_QCA9377_lcd-800x480_20181102.zip

The frequency i get is 53Hz:
```
root@pico-imx7:~# cat /sys/class/graphics/fb0/modes
U:800x480p-53
U:800x480i-53
```
Please check the settings of device node `lcdif` in `arch/arm/boot/dts/imx7d-pico.dtsi`:
```
&lcdif {
	pinctrl-names = "default";
	pinctrl-0 = <&pinctrl_lcdif_dat
		     &pinctrl_lcdif_ctrl>;
	lcd-supply = <&lcd_on>;
	display = <&display0>;
	status = "okay";

	display0: display {
		bits-per-pixel = <32>;
		bus-width = <24>;

		display-timings {
			native-mode = <&timing0>;
			timing0: timing0 {
				clock-frequency = <33260000>;
				hactive = <800>;
				vactive = <480>;
				hback-porch = <11>;
				hfront-porch = <11>;
				vback-porch = <12>;
				vfront-porch = <11>;
				hsync-len = <46>;
				vsync-len = <210>;
				hsync-active = <0>;
				vsync-active = <0>;
				de-active = <1>;
				pixelclk-active = <1>;
				interlaced =  <0>;
			};
		};
	};
};
```
`drivers/video/fbdev/mxsfb.c` gets the information from `lcdif` to calculate frequency. 
(I didn't really dig into it. )

BR,

Richard

**Comment by jwinarske** [comment]
Okay I sorted that out for the kernel.  The timing was wildly off from the display spec.  I'm surprised it worked...

Where is the timing config for u-boot, as the TechNexion logo is far off to the right, and clipped.

**Comment by jwinarske** [comment]
Okay I'm all set.  The timing was set wrong in both boot and kernel dts.  Thanks!
