### ISSUE TITLE
QCA9377 and Connman

### ISSUE THREAD

**Issue by atnock** [TechNexion/meta-edm-bsp-release#6]
Hi Technexion :),

I'm working on the TC-0710 with the new QCA wifi card. I'm using the reference image "core-image-salto"  with one change : i had connman-client in order to have connmanctl.

On the example below i'm trying to connect to an open wi-fi network called PLOPINOU. The TC-0710 is the only device on this access point. And this access point work with other device like phone or TEP-1560-IMX6. 

```root@edm-imx6:~# connmanctl
connmanctl> agent on
Agent registered
connmanctl> scan wifi
Scan completed for wifi
connmanctl> services
    TEST1                wifi_001f7b310080_****_managed_ieee8021x
    TEST1                wifi_021f7bb50080_****_managed_ieee8021x
    TEST2                wifi_001f7b310080_****_managed_psk
    TEST2                wifi_021f7bb50080_****_managed_psk
    PLOPINOU             wifi_021f7bb50080_****_managed_none
    PLOPINOU             wifi_001f7b310080_****_managed_none
connmanctl> services wifi_021f7bb50080_****_managed_none
/net/connman/service/wifi_021f7bb50080_****_managed_none
  Type = wifi
  Security = [ none ]
  State = idle
  Strength = 84
  Favorite = False
  Immutable = False
  AutoConnect = False
  Name = PLOPINOU
  Ethernet = [ Method=auto, Interface=p2p0, Address=02:1F:7B:**:**:**, MTU=1500 ]
  IPv4 = [  ]
  IPv4.Configuration = [ Method=dhcp ]
  IPv6 = [  ]
  IPv6.Configuration = [ Method=off ]
  Nameservers = [  ]
  Nameservers.Configuration = [  ]
  Timeservers = [  ]
  Timeservers.Configuration = [  ]
  Domains = [  ]
  Domains.Configuration = [  ]
  Proxy = [  ]
  Proxy.Configuration = [  ]
  Provider = [  ]
connmanctl> connect wifi_021f7bb50080_****_managed_none
connmanctl> services
  a  PLOPINOU             wifi_021f7bb50080_****_managed_none
     PLOPINOU             wifi_001f7b310080_****_managed_none
     TEST1                wifi_001f7b310080_****_managed_ieee8021x
     TEST1                wifi_021f7bb50080_****_managed_ieee8021x
     TEST2                wifi_001f7b310080_****_managed_psk
     TEST2                wifi_021f7bb50080_****_managed_psk
connmanctl>
Error /net/connman/service/wifi_021f7bb50080_****_managed_none: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
connmanctl> services
     PLOPINOU             wifi_021f7bb50080_****_managed_none
     PLOPINOU             wifi_001f7b310080_****_managed_none
     TEST1                wifi_001f7b310080_****_managed_ieee8021x
     TEST1                wifi_021f7bb50080_****_managed_ieee8021x
     TEST2                wifi_001f7b310080_****_managed_psk
     TEST2                wifi_021f7bb50080_****_managed_psk
connmanctl>
```

When I'm trying to connect to this access point connman return this error  : 
**Error /net/connman/service/wifi_021f7bb50080_****_managed_none: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.**
Furthermore every network is listed twice.

Finally i can't connect to my access point. But it's working well with iw on the same hardware (no twice wifi network and connection ok) and the same connman is working well too on a TEP-1560-IMX6.

Do you with any idea about the problem ? Can you reproduce this issue on your own hardware ?

Thank you,

**Comment by Henriparm** [comment]
Hello, 
in the following string:
wifi_001f7b311132_544543484e4558494f4e28354729_managed_psk
The prefix **001f7b** is the MAC address specifically for TechNexion WIFI chips.

The second string
wifi_021f7bb51132_544543484e4558494f4e28354729_managed_psk
The prefix **021f7b** is the virtual MAC address generated for p2p interface. (Note: This virtual MAC address follows the administered addresses rule to be generated.)
If you don't want p2p to show in hotspot scan:
iw dev p2p0 del
